# Generated by Django 3.1.3 on 2022-03-12 11:42

import database_main.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('budgetMonth', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=database_main.models.get_timezone_month)),
                ('budgetYear', models.IntegerField(default=database_main.models.get_timezone_year)),
                ('budgetIncome', models.IntegerField(default=0)),
                ('budgetExpenses', models.IntegerField(default=0)),
                ('budgetSavings', models.IntegerField(default=0)),
                ('budgetGoal', models.IntegerField(default=0)),
                ('budgetIndex', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('incomeAmount', models.IntegerField(default=0)),
                ('incomeSource', models.CharField(default='general', max_length=100)),
                ('incomeBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomeBudget', to='database_main.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expenseAmount', models.IntegerField(default=0)),
                ('expenseSource', models.CharField(default='general', max_length=100)),
                ('expenseBudget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseBudget', to='database_main.budget')),
            ],
        ),
    ]
